# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import doc_pb2 as doc__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in doc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CollaborativeDocumentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EditDocument = channel.stream_stream(
                '/CollaborativeDocument/EditDocument',
                request_serializer=doc__pb2.Transfer.SerializeToString,
                response_deserializer=doc__pb2.Transfer.FromString,
                _registered_method=True)


class CollaborativeDocumentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EditDocument(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CollaborativeDocumentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EditDocument': grpc.stream_stream_rpc_method_handler(
                    servicer.EditDocument,
                    request_deserializer=doc__pb2.Transfer.FromString,
                    response_serializer=doc__pb2.Transfer.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CollaborativeDocument', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('CollaborativeDocument', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CollaborativeDocument(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EditDocument(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/CollaborativeDocument/EditDocument',
            doc__pb2.Transfer.SerializeToString,
            doc__pb2.Transfer.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LoggerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LogChanges = channel.unary_unary(
                '/Logger/LogChanges',
                request_serializer=doc__pb2.LogEntry.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class LoggerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LogChanges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoggerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LogChanges': grpc.unary_unary_rpc_method_handler(
                    servicer.LogChanges,
                    request_deserializer=doc__pb2.LogEntry.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Logger', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Logger', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Logger(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LogChanges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Logger/LogChanges',
            doc__pb2.LogEntry.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
